version: '3.8'
services:
  ScanServer:
    image: artifactory.gdata.de:6555/development/vaas/gdatasoftwareag/scanserver:1.5.2
    restart: always
    stop_grace_period: 120s
    volumes:
      - samples:/tmp/scan
      - scanSocket:/var/share/run

  ScanClient:
    image: artifactory.gdata.de:6555/development/vaas/gdatasoftwareag/scanclient:1.5.2
    restart: always
    stop_grace_period: 120s
    ports:
      - 8080:8080
    volumes:
      - samples:/tmp/scan
      - scanSocket:/var/share/run

volumes:
  samples:
  scanSocket:

