replicaCount: 1
server:
  name: server
  image:
    repository: ghcr.io/gdatasoftwareag/scanserver
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
client:
  name: client
  image:
    repository: ghcr.io/gdatasoftwareag/scanclient
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

imagePullSecrets:
  - name: gdscanregistry

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

secret:
  dockerconfigjson: ""

service:
  type: ""
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: gdscan.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  server:
    limits:
      cpu: 4
      memory: 2Gi
    requests:
      cpu: 2
      memory: 1Gi
  client:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  memory: false
  size: 5Gi
  storageClass: ""
autoUpdate:
  enabled: true
  # every hour
  schedule: "0 * * * *"
