replicaCount: 1
deploymentStrategy: "Recreate"
server:
  name: server
  image:
    repository: ghcr.io/gdatasoftwareag/scanserver
    pullPolicy: Always
    tag: 1.2.17
client:
  name: client
  image:
    repository: ghcr.io/gdatasoftwareag/scanclient
    pullPolicy: Always
    tag: 1.2.17

imagePullSecrets:
  - name: gdscanregistry

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

secret:
  dockerconfigjson: ""

service:
  type: ""
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: gdscan.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  server:
    limits:
      cpu: 4
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  client:
    limits:
      cpu: 1
      memory: 128Mi
    requests:
      cpu: 1
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 20
  targetCPU: 75

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  memory: false
  size: 5Gi
  storageClass: ""
autoUpdate:
  enabled: true
  # every hour
  schedule: "0 * * * *"
