replicaCount: 1
server:
  name: server
  image:
    repository: ghcr.io/gdatasoftwareag/scanserver
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
client:
  name: client
  image:
    repository: ghcr.io/gdatasoftwareag/scanclient
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

imagePullSecrets:
  - name: gdscanregistry

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

secret:
  dockerconfigjson: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: gdscan.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  server:
    limits:
      cpu: 4
      memory: 2Gi
    requests:
      cpu: 2
      memory: 1Gi
  client:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  memory: false
  accessModes:
    - ReadWriteMany
  size: 5Gi
  storageClass: ""
