apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gdscan.fullname" . }}
  labels:
    {{- include "gdscan.labels" . | nindent 4 }}
spec:
  strategy:
    type: "Recreate"
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gdscan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gdscan.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: samples
        {{- if .Values.persistence.enabled }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: 
                {{- range .Values.persistence.accessModes }}
                  - {{ . | quote }}
                {{- end }}
                {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 2 }}
                resources:
                  requests:
                    storage: 10Gi
        {{- else }}
          emptyDir:
            sizeLimit: {{ .Values.persistence.size | quote }}
          {{- if .Values.persistence.memory }}
            medium : "Memory"
          {{- end }}
        {{- end }}
        - name: scan-socket
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.server.name }}
          env:
            - name: date
              value: "{{ now | unixEpoch }}"
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          volumeMounts:
            - name: samples
              mountPath: /tmp/scan
            - name: scan-socket
              mountPath: /var/share/run
          resources:
            {{- toYaml .Values.resources.server | nindent 12 }}
        - name: {{ .Values.client.name }}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          volumeMounts:
            - name: samples
              mountPath: /tmp/scan
            - name: scan-socket
              mountPath: /var/share/run
          resources:
            {{- toYaml .Values.resources.client | nindent 12 }}
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
